micronaut:
  application:
    name: keymanagerRest
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

info:
  app:
    name: KeymanagerRest
    version: 1.0
    kotlin-version: 1.4.30
    micronaut-version: 2.3.4

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: ${KEYMANAGER_GRPC_URL:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 10

healthcheck:
  keymanager:
    url: http://${HEALTHCHECK_KEYMANAGER_HOST:localhost}:${HEALTHCHECK_KEYMANAGER_PORT:8080}/${HEALTHCHECK_KEYMANAGER_ENDPOINT:check-grpc-status}

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  info:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false

tracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    sampler:
      probability: ${JAEGER_SAMPLE:1}
    sender:
      endpoint: ${JAEGER_ENDPOINT:`http://localhost:14268/api/traces`}
    reporter:
      flushInterval: 2000
      maxQueueSize: 200